name: Scrape Overdue Invoices

on:
  schedule:
    # 11am and 11pm NZT (UTC+12/13)
    - cron: '0 22,11 * * 1-5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DISCOVER_USERNAME: ${{ secrets.DISCOVER_USERNAME }}
          DISCOVER_PASSWORD: ${{ secrets.DISCOVER_PASSWORD }}
        run: node scripts/playwright-scrape-overdue.js