# Generated by Django 5.2.4 on 2025-07-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_id', models.CharField(blank=True, help_text='Discover API ID', max_length=50, null=True, unique=True)),
                ('moe_number', models.CharField(blank=True, help_text='MOE Number', max_length=50, null=True)),
                ('u2_licensed', models.PositiveIntegerField(blank=True, help_text='Licensed U2 children', null=True)),
                ('total_licensed', models.PositiveIntegerField(blank=True, help_text='Licensed Total children', null=True)),
                ('overdue_invoice_amount', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cleaning Supplies', 'Cleaning Supplies'), ('First Aid', 'First Aid'), ('Food Costs', 'Food Costs'), ('Kiri Classroom Resources', 'Kiri Classroom Resources'), ('Wai Classroom Resources', 'Wai Classroom Resources'), ('Nga Classroom Resources', 'Nga Classroom Resources'), ('Centre Purcahses', 'Centre Purcahses'), ('Printing and Stationary', 'Printing and Stationary'), ('Art and Messy Play', 'Art and Messy Play'), ('Meeting Costs', 'Meeting Costs'), ('Nappies and Wipes', 'Nappies and Wipes'), ('Repairs and Maintenance', 'Repairs and Maintenance')], max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, help_text='Default monthly budget', max_digits=10)),
                ('jan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jun', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nov', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['category', 'year'],
                'unique_together': {('category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=7)),
                ('u2', models.PositiveSmallIntegerField(help_text='U2 occupancy percentage')),
                ('o2', models.PositiveSmallIntegerField(help_text='O2 occupancy percentage')),
                ('total', models.PositiveSmallIntegerField(help_text='Total occupancy percentage')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupancy.centre')),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('centre', 'month_year')},
            },
        ),
    ]
