# Generated by Django 5.2.4 on 2025-07-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=7)),
                ('u2', models.PositiveSmallIntegerField(help_text='U2 occupancy percentage')),
                ('o2', models.PositiveSmallIntegerField(help_text='O2 occupancy percentage')),
                ('total', models.PositiveSmallIntegerField(help_text='Total occupancy percentage')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupancy.centre')),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('centre', 'month_year')},
            },
        ),
    ]
