# Generated by Django 5.2.4 on 2025-07-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='api_id',
            field=models.CharField(blank=True, help_text='External API ID', max_length=50, null=True, unique=True),
        ),
    ]
