# Generated by Django 5.2.4 on 2025-07-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0003_alter_centre_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='licensed',
            field=models.JSONField(blank=True, help_text='Licensed numbers for U2 and Total', null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='moe_number',
            field=models.CharField(blank=True, help_text='MOE Number', max_length=50, null=True),
        ),
    ]
