# Generated by Django 5.2.4 on 2025-07-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0004_centre_licensed_centre_moe_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='licensed',
        ),
        migrations.AddField(
            model_name='centre',
            name='total_licensed',
            field=models.PositiveIntegerField(blank=True, help_text='Licensed Total children', null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='u2_licensed',
            field=models.PositiveIntegerField(blank=True, help_text='Licensed U2 children', null=True),
        ),
    ]
