# Generated by Django 5.2.4 on 2025-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0005_remove_centre_licensed_centre_total_licensed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='overdue_invoice_amount',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
