name: Enrolment Status Sync

on:
  schedule:
    # One-off run for 1:30pm NZT (1:30am UTC) on 16th September 2025
    - cron: '30 1 16 9 *' # 1:30 UTC, 16th September
    # Regular schedule: 11pm NZT is 12pm UTC (NZT is UTC+12, adjust for daylight savings if needed)
    - cron: '0 12 * * 1-5' # 12:00 UTC, Mon-Fri

jobs:
  sync-enrolment-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Playwright script
        run: node childcare-dashboard/scripts/playwright-scrape-overdue.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DISCOVER_USERNAME: ${{ secrets.DISCOVER_USERNAME }}
          DISCOVER_PASSWORD: ${{ secrets.DISCOVER_PASSWORD }}
