- name: Debug DIRECT_URL (masked)
  env:
    DIRECT_URL: ${{ secrets.DIRECT_URL }}
  run: |
    echo "DIRECT_URL: $(echo $DIRECT_URL | sed 's/HotelLimaFox3!/************/g')"

- name: Fail if DIRECT_URL is empty
  env:
    DIRECT_URL: ${{ secrets.DIRECT_URL }}
  run: |
    if [ -z "$DIRECT_URL" ]; then
      echo "DIRECT_URL is not set!"
      exit 1
    fi

- name: Connectivity check (explicit params)
  env:
    DIRECT_URL: ${{ secrets.DIRECT_URL }}
  run: |
    sudo apt-get update && sudo apt-get install -y postgresql-client
    export PGPASSWORD="HotelLimaFox3!"
    psql -h db.lhismadtghpgvuuxioen.supabase.co -U postgres -d postgres -p 5432 -c "select version();" "sslmode=require"
